"""
holdings.py — Top-20 holdings per SPDR sector ETF.

Single source of truth shared between Python scoring and web display.
"""

from __future__ import annotations

from config import SECTOR_ETFS

# yfinance uses hyphens for tickers that have a dot in the symbol
YF_SYMBOL_MAP: dict = {
    "BRK.B": "BRK-B",
    "BRK.A": "BRK-A",
}


def yf_ticker(ticker: str) -> str:
    """Return the yfinance-compatible symbol for a ticker (e.g. BRK.B → BRK-B)."""
    return YF_SYMBOL_MAP.get(ticker, ticker)


SECTOR_HOLDINGS: dict = {
    "XLK": [
        {"ticker": "AAPL",  "name": "Apple"},
        {"ticker": "MSFT",  "name": "Microsoft"},
        {"ticker": "NVDA",  "name": "NVIDIA"},
        {"ticker": "AVGO",  "name": "Broadcom"},
        {"ticker": "ORCL",  "name": "Oracle"},
        {"ticker": "CRM",   "name": "Salesforce"},
        {"ticker": "CSCO",  "name": "Cisco Systems"},
        {"ticker": "AMD",   "name": "Advanced Micro Devices"},
        {"ticker": "ADBE",  "name": "Adobe"},
        {"ticker": "ACN",   "name": "Accenture"},
        {"ticker": "IBM",   "name": "IBM"},
        {"ticker": "NOW",   "name": "ServiceNow"},
        {"ticker": "INTU",  "name": "Intuit"},
        {"ticker": "PLTR",  "name": "Palantir Technologies"},
        {"ticker": "TXN",   "name": "Texas Instruments"},
        {"ticker": "APP",   "name": "AppLovin"},
        {"ticker": "QCOM",  "name": "Qualcomm"},
        {"ticker": "PANW",  "name": "Palo Alto Networks"},
        {"ticker": "MU",    "name": "Micron Technology"},
        {"ticker": "ADI",   "name": "Analog Devices"},
    ],
    "XLV": [
        {"ticker": "LLY",   "name": "Eli Lilly"},
        {"ticker": "UNH",   "name": "UnitedHealth Group"},
        {"ticker": "JNJ",   "name": "Johnson & Johnson"},
        {"ticker": "ABBV",  "name": "AbbVie"},
        {"ticker": "MRK",   "name": "Merck"},
        {"ticker": "PFE",   "name": "Pfizer"},
        {"ticker": "TMO",   "name": "Thermo Fisher Scientific"},
        {"ticker": "ABT",   "name": "Abbott Laboratories"},
        {"ticker": "AMGN",  "name": "Amgen"},
        {"ticker": "GILD",  "name": "Gilead Sciences"},
        {"ticker": "BMY",   "name": "Bristol-Myers Squibb"},
        {"ticker": "DHR",   "name": "Danaher"},
        {"ticker": "BSX",   "name": "Boston Scientific"},
        {"ticker": "ISRG",  "name": "Intuitive Surgical"},
        {"ticker": "VRTX",  "name": "Vertex Pharmaceuticals"},
        {"ticker": "SYK",   "name": "Stryker"},
        {"ticker": "MDT",   "name": "Medtronic"},
        {"ticker": "ELV",   "name": "Elevance Health"},
        {"ticker": "MCK",   "name": "McKesson"},
        {"ticker": "CI",    "name": "Cigna"},
    ],
    "XLF": [
        {"ticker": "BRK.B", "name": "Berkshire Hathaway"},
        {"ticker": "JPM",   "name": "JPMorgan Chase"},
        {"ticker": "V",     "name": "Visa"},
        {"ticker": "MA",    "name": "Mastercard"},
        {"ticker": "BAC",   "name": "Bank of America"},
        {"ticker": "WFC",   "name": "Wells Fargo"},
        {"ticker": "SPGI",  "name": "S&P Global"},
        {"ticker": "GS",    "name": "Goldman Sachs"},
        {"ticker": "MS",    "name": "Morgan Stanley"},
        {"ticker": "SCHW",  "name": "Charles Schwab"},
        {"ticker": "AXP",   "name": "American Express"},
        {"ticker": "PGR",   "name": "Progressive"},
        {"ticker": "BX",    "name": "Blackstone"},
        {"ticker": "BLK",   "name": "BlackRock"},
        {"ticker": "C",     "name": "Citigroup"},
        {"ticker": "MMC",   "name": "Marsh McLennan"},
        {"ticker": "CB",    "name": "Chubb"},
        {"ticker": "APO",   "name": "Apollo Global Management"},
        {"ticker": "KKR",   "name": "KKR & Co."},
        {"ticker": "AON",   "name": "Aon"},
    ],
    "XLE": [
        {"ticker": "XOM",   "name": "ExxonMobil"},
        {"ticker": "CVX",   "name": "Chevron"},
        {"ticker": "COP",   "name": "ConocoPhillips"},
        {"ticker": "EOG",   "name": "EOG Resources"},
        {"ticker": "SLB",   "name": "Schlumberger"},
        {"ticker": "MPC",   "name": "Marathon Petroleum"},
        {"ticker": "PSX",   "name": "Phillips 66"},
        {"ticker": "VLO",   "name": "Valero Energy"},
        {"ticker": "WMB",   "name": "Williams Companies"},
        {"ticker": "OXY",   "name": "Occidental Petroleum"},
        {"ticker": "KMI",   "name": "Kinder Morgan"},
        {"ticker": "OKE",   "name": "ONEOK"},
        {"ticker": "HES",   "name": "Hess"},
        {"ticker": "HAL",   "name": "Halliburton"},
        {"ticker": "BKR",   "name": "Baker Hughes"},
        {"ticker": "DVN",   "name": "Devon Energy"},
        {"ticker": "FANG",  "name": "Diamondback Energy"},
        {"ticker": "CTRA",  "name": "Coterra Energy"},
        {"ticker": "TRGP",  "name": "Targa Resources"},
        {"ticker": "EQT",   "name": "EQT Corporation"},
    ],
    "XLI": [
        {"ticker": "GE",    "name": "GE Aerospace"},
        {"ticker": "RTX",   "name": "RTX Corporation"},
        {"ticker": "CAT",   "name": "Caterpillar"},
        {"ticker": "BA",    "name": "Boeing"},
        {"ticker": "HON",   "name": "Honeywell"},
        {"ticker": "UNP",   "name": "Union Pacific"},
        {"ticker": "LMT",   "name": "Lockheed Martin"},
        {"ticker": "ADP",   "name": "Automatic Data Processing"},
        {"ticker": "ETN",   "name": "Eaton"},
        {"ticker": "DE",    "name": "Deere & Co."},
        {"ticker": "GEV",   "name": "GE Vernova"},
        {"ticker": "NOC",   "name": "Northrop Grumman"},
        {"ticker": "WM",    "name": "Waste Management"},
        {"ticker": "EMR",   "name": "Emerson Electric"},
        {"ticker": "CSX",   "name": "CSX Corporation"},
        {"ticker": "NSC",   "name": "Norfolk Southern"},
        {"ticker": "ITW",   "name": "Illinois Tool Works"},
        {"ticker": "PH",    "name": "Parker-Hannifin"},
        {"ticker": "CTAS",  "name": "Cintas"},
        {"ticker": "PCAR",  "name": "PACCAR"},
    ],
    "XLY": [
        {"ticker": "AMZN",  "name": "Amazon"},
        {"ticker": "TSLA",  "name": "Tesla"},
        {"ticker": "HD",    "name": "Home Depot"},
        {"ticker": "MCD",   "name": "McDonald's"},
        {"ticker": "BKNG",  "name": "Booking Holdings"},
        {"ticker": "TJX",   "name": "TJX Companies"},
        {"ticker": "LOW",   "name": "Lowe's"},
        {"ticker": "SBUX",  "name": "Starbucks"},
        {"ticker": "MAR",   "name": "Marriott International"},
        {"ticker": "NVR",   "name": "NVR Inc."},
        {"ticker": "CMG",   "name": "Chipotle Mexican Grill"},
        {"ticker": "AZO",   "name": "AutoZone"},
        {"ticker": "ORLY",  "name": "O'Reilly Automotive"},
        {"ticker": "F",     "name": "Ford Motor"},
        {"ticker": "HLT",   "name": "Hilton Worldwide"},
        {"ticker": "ROST",  "name": "Ross Stores"},
        {"ticker": "YUM",   "name": "Yum! Brands"},
        {"ticker": "GM",    "name": "General Motors"},
        {"ticker": "RCL",   "name": "Royal Caribbean"},
        {"ticker": "EBAY",  "name": "eBay"},
    ],
    "XLP": [
        {"ticker": "COST",  "name": "Costco Wholesale"},
        {"ticker": "WMT",   "name": "Walmart"},
        {"ticker": "PG",    "name": "Procter & Gamble"},
        {"ticker": "KO",    "name": "Coca-Cola"},
        {"ticker": "PM",    "name": "Philip Morris International"},
        {"ticker": "PEP",   "name": "PepsiCo"},
        {"ticker": "MDLZ",  "name": "Mondelez International"},
        {"ticker": "MO",    "name": "Altria Group"},
        {"ticker": "CL",    "name": "Colgate-Palmolive"},
        {"ticker": "TGT",   "name": "Target"},
        {"ticker": "KMB",   "name": "Kimberly-Clark"},
        {"ticker": "SYY",   "name": "Sysco"},
        {"ticker": "GIS",   "name": "General Mills"},
        {"ticker": "EL",    "name": "Estée Lauder"},
        {"ticker": "KR",    "name": "Kroger"},
        {"ticker": "STZ",   "name": "Constellation Brands"},
        {"ticker": "KHC",   "name": "Kraft Heinz"},
        {"ticker": "HSY",   "name": "Hershey"},
        {"ticker": "ADM",   "name": "Archer-Daniels-Midland"},
        {"ticker": "WBA",   "name": "Walgreens Boots Alliance"},
    ],
    "XLU": [
        {"ticker": "NEE",   "name": "NextEra Energy"},
        {"ticker": "SO",    "name": "Southern Company"},
        {"ticker": "DUK",   "name": "Duke Energy"},
        {"ticker": "CEG",   "name": "Constellation Energy"},
        {"ticker": "AEP",   "name": "American Electric Power"},
        {"ticker": "SRE",   "name": "Sempra"},
        {"ticker": "VST",   "name": "Vistra"},
        {"ticker": "D",     "name": "Dominion Energy"},
        {"ticker": "PEG",   "name": "Public Service Enterprise Group"},
        {"ticker": "EXC",   "name": "Exelon"},
        {"ticker": "XEL",   "name": "Xcel Energy"},
        {"ticker": "PCG",   "name": "PG&E"},
        {"ticker": "EIX",   "name": "Edison International"},
        {"ticker": "ED",    "name": "Consolidated Edison"},
        {"ticker": "WEC",   "name": "WEC Energy Group"},
        {"ticker": "AWK",   "name": "American Water Works"},
        {"ticker": "ES",    "name": "Eversource Energy"},
        {"ticker": "DTE",   "name": "DTE Energy"},
        {"ticker": "ETR",   "name": "Entergy"},
        {"ticker": "AES",   "name": "AES Corporation"},
    ],
    "XLB": [
        {"ticker": "LIN",   "name": "Linde"},
        {"ticker": "SHW",   "name": "Sherwin-Williams"},
        {"ticker": "ECL",   "name": "Ecolab"},
        {"ticker": "APD",   "name": "Air Products and Chemicals"},
        {"ticker": "FCX",   "name": "Freeport-McMoRan"},
        {"ticker": "NEM",   "name": "Newmont"},
        {"ticker": "NUE",   "name": "Nucor"},
        {"ticker": "DOW",   "name": "Dow Inc."},
        {"ticker": "DD",    "name": "DuPont de Nemours"},
        {"ticker": "PPG",   "name": "PPG Industries"},
        {"ticker": "VMC",   "name": "Vulcan Materials"},
        {"ticker": "MLM",   "name": "Martin Marietta Materials"},
        {"ticker": "IFF",   "name": "International Flavors & Fragrances"},
        {"ticker": "STLD",  "name": "Steel Dynamics"},
        {"ticker": "MOS",   "name": "Mosaic"},
        {"ticker": "CF",    "name": "CF Industries"},
        {"ticker": "ALB",   "name": "Albemarle"},
        {"ticker": "LYB",   "name": "LyondellBasell Industries"},
        {"ticker": "AVY",   "name": "Avery Dennison"},
        {"ticker": "CE",    "name": "Celanese"},
    ],
    "XLRE": [
        {"ticker": "PLD",   "name": "Prologis"},
        {"ticker": "AMT",   "name": "American Tower"},
        {"ticker": "WELL",  "name": "Welltower"},
        {"ticker": "EQIX",  "name": "Equinix"},
        {"ticker": "DLR",   "name": "Digital Realty Trust"},
        {"ticker": "PSA",   "name": "Public Storage"},
        {"ticker": "CCI",   "name": "Crown Castle"},
        {"ticker": "O",     "name": "Realty Income"},
        {"ticker": "SPG",   "name": "Simon Property Group"},
        {"ticker": "CBRE",  "name": "CBRE Group"},
        {"ticker": "IRM",   "name": "Iron Mountain"},
        {"ticker": "EXR",   "name": "Extra Space Storage"},
        {"ticker": "AVB",   "name": "AvalonBay Communities"},
        {"ticker": "EQR",   "name": "Equity Residential"},
        {"ticker": "VICI",  "name": "VICI Properties"},
        {"ticker": "WY",    "name": "Weyerhaeuser"},
        {"ticker": "VTR",   "name": "Ventas"},
        {"ticker": "INVH",  "name": "Invitation Homes"},
        {"ticker": "MAA",   "name": "Mid-America Apartment Communities"},
        {"ticker": "DOC",   "name": "Healthpeak Properties"},
    ],
    "XLC": [
        {"ticker": "META",  "name": "Meta Platforms"},
        {"ticker": "GOOGL", "name": "Alphabet (Class A)"},
        {"ticker": "GOOG",  "name": "Alphabet (Class C)"},
        {"ticker": "NFLX",  "name": "Netflix"},
        {"ticker": "TMUS",  "name": "T-Mobile US"},
        {"ticker": "DIS",   "name": "Walt Disney"},
        {"ticker": "T",     "name": "AT&T"},
        {"ticker": "VZ",    "name": "Verizon Communications"},
        {"ticker": "CMCSA", "name": "Comcast"},
        {"ticker": "CHTR",  "name": "Charter Communications"},
        {"ticker": "EA",    "name": "Electronic Arts"},
        {"ticker": "TTWO",  "name": "Take-Two Interactive"},
        {"ticker": "WBD",   "name": "Warner Bros. Discovery"},
        {"ticker": "LYV",   "name": "Live Nation Entertainment"},
        {"ticker": "NWSA",  "name": "News Corp (Class A)"},
        {"ticker": "NWS",   "name": "News Corp (Class B)"},
        {"ticker": "FOX",   "name": "Fox Corporation (Class B)"},
        {"ticker": "FOXA",  "name": "Fox Corporation (Class A)"},
        {"ticker": "IPG",   "name": "Interpublic Group"},
        {"ticker": "OMC",   "name": "Omnicom Group"},
    ],
}


def all_holdings() -> list:
    """Return all holdings as a flat list of dicts with yf_ticker added."""
    out = []
    for sector, holdings in SECTOR_HOLDINGS.items():
        for h in holdings:
            out.append({
                "sector":      sector,
                "sector_name": SECTOR_ETFS[sector],
                "ticker":      h["ticker"],
                "yf_ticker":   yf_ticker(h["ticker"]),
                "name":        h["name"],
            })
    return out


def all_yf_tickers() -> list:
    """Unique list of yfinance-format tickers for all holdings."""
    seen = set()
    out = []
    for h in all_holdings():
        t = h["yf_ticker"]
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out
